# rustup toolchain install nightly
# rustup override set nightly
[package]
name = "stm32"
version = "0.1.0"
authors = ["Yusef Karim <yusefkarim@riseup.net>"]
edition = "2018"

[profile.dev]
# Optimize for size
opt-level = 's'
# Link with link time optimization (lto)
lto = true
# Enable debugging
debug = false

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'


[dependencies]
# Semihosting for ARM Cortex-M processors
# https://docs.rs/cortex-m-semihosting/0.3.4/cortex_m_semihosting/
# cortex-m-semihosting = "0.3.4"

# Provides panic handler for halting the CPU (in an infinite loop)
# https://lib.rs/crates/panic-halt
panic-halt = "0.2.0"

# Concurrency framework
# https://github.com/rtfm-rs/cortex-m-rtfm
cortex-m-rtfm = "0.5.0-beta.1"

# Data structures
# https://docs.rs/heapless/0.5.1/heapless/
heapless = "0.5.1"

# Provides low-level access to registers and assembly instructions
# https://docs.rs/cortex-m/0.6.1/cortex_m/
cortex-m = "0.6.1"

# Provides startup code and useful attributes
# https://docs.rs/cortex-m-rt/0.6.10/cortex_m_rt/
cortex-m-rt = "0.6.10"

# Autogenerated API for the STM32F1 peripherals
# https://docs.rs/stm32f1/0.8.0/stm32f1/stm32f103/index.html
stm32f1 = {version = "0.8.0", features = ["stm32f103", "rt"]}

# A Hardware Abstraction Layer (HAL) for embedded systems
# https://docs.rs/embedded-hal/0.2.3/embedded_hal/
embedded-hal = "0.2.3"

# Hardware Abstraction Library for STM32F1
# https://docs.rs/stm32f1xx-hal/0.4.0/stm32f1xx_hal
stm32f1xx-hal = {version = "0.4.0", features = ["rt", "stm32f103"]} 
